# Generated by Django 4.2.14 on 2024-07-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_recipe_updated_at_alter_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating_avg',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
