# Generated by Django 4.2.14 on 2024-07-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_rating_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating_avg',
        ),
    ]
